// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2lCfaulYk5UEfhEGw-ULmGy9KX8VTTWw',
    appId: '1:179906622537:web:ea9bde60f976680b477b98',
    messagingSenderId: '179906622537',
    projectId: 'wasel-2ac78',
    authDomain: 'wasel-2ac78.firebaseapp.com',
    storageBucket: 'wasel-2ac78.firebasestorage.app',
    measurementId: 'G-178BNJZHDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx59dxQ7DElB5jHULYZhuDly2UUAyVvEA',
    appId: '1:179906622537:android:9851689dbb2e7e4b477b98',
    messagingSenderId: '179906622537',
    projectId: 'wasel-2ac78',
    storageBucket: 'wasel-2ac78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoA_Vlm9OW01rMuEL2kXziOXLtcSuI_8g',
    appId: '1:179906622537:ios:8d35d6754d81f290477b98',
    messagingSenderId: '179906622537',
    projectId: 'wasel-2ac78',
    storageBucket: 'wasel-2ac78.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoA_Vlm9OW01rMuEL2kXziOXLtcSuI_8g',
    appId: '1:179906622537:ios:8d35d6754d81f290477b98',
    messagingSenderId: '179906622537',
    projectId: 'wasel-2ac78',
    storageBucket: 'wasel-2ac78.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2lCfaulYk5UEfhEGw-ULmGy9KX8VTTWw',
    appId: '1:179906622537:web:55ad3f76f5dcbdd2477b98',
    messagingSenderId: '179906622537',
    projectId: 'wasel-2ac78',
    authDomain: 'wasel-2ac78.firebaseapp.com',
    storageBucket: 'wasel-2ac78.firebasestorage.app',
    measurementId: 'G-M8P13M53HJ',
  );
}
